import { Command } from 'commander';
import chalk from 'chalk';
import { execSync } from 'node:child_process';
import { storage } from '../core/storage.js';
import { ensureInit } from '../core/ensure-init.js';

interface ExportData {
  projectName: string;
  context: string | null;
  prototypes: ExportPrototype[];
  stats: { prototypes: number; groups: number; versions: number };
}

interface ExportPrototype {
  id: string;
  name: string;
  description: string;
  groups: ExportGroup[];
}

interface ExportGroup {
  id: string;
  name: string;
  description?: string;
  brief: string | null;
  categories: Record<string, ExportScenario[]>;
}

interface ExportScenario {
  name: string;
  subVersions: ExportVersion[];
}

interface ExportVersion {
  id: string;
  description?: string;
  tags: string[];
  starred: boolean;
  notes?: string;
  author: string;
  timestamp: string;
  files: string[];
}

async function buildExportData(filterGroupId?: string): Promise<ExportData> {
  const config = await storage.getConfig();
  const context = await storage.readContext();
  const prototypes = await storage.listPrototypes();

  const exportProtos: ExportPrototype[] = [];
  let totalGroups = 0;
  let totalVersions = 0;

  for (const proto of prototypes) {
    let groups = await storage.listGroups(proto.id);
    if (filterGroupId) {
      groups = groups.filter((g) => g.id === filterGroupId);
    }
    if (groups.length === 0 && filterGroupId) continue;

    const exportGroups: ExportGroup[] = [];

    for (const group of groups) {
      const brief = await storage.readGroupBrief(proto.id, group.id);
      const versions = await storage.listVersions(proto.id, group.id);
      totalVersions += versions.length;

      const byCategory = new Map<string, typeof versions>();
      for (const v of versions) {
        const cat = v.category || 'Uncategorized';
        if (!byCategory.has(cat)) byCategory.set(cat, []);
        byCategory.get(cat)!.push(v);
      }

      const categories: Record<string, ExportScenario[]> = {};
      for (const [cat, catVersions] of byCategory) {
        const scenarioNames = [...new Set(catVersions.map((v) => v.name))];
        categories[cat] = [];
        for (const name of scenarioNames) {
          const subs = catVersions.filter((v) => v.name === name);
          const subVersions: ExportVersion[] = [];
          for (const v of subs) {
            const files = await storage.listVersionFiles(proto.id, v.id);
            subVersions.push({
              id: v.id,
              description: v.description,
              tags: v.tags,
              starred: v.starred,
              notes: v.notes,
              author: v.author,
              timestamp: v.timestamp,
              files,
            });
          }
          categories[cat].push({ name, subVersions });
        }
      }

      exportGroups.push({
        id: group.id,
        name: group.name,
        description: group.description,
        brief,
        categories,
      });
    }

    totalGroups += exportGroups.length;
    if (exportGroups.length > 0) {
      exportProtos.push({
        id: proto.id,
        name: proto.name,
        description: proto.description,
        groups: exportGroups,
      });
    }
  }

  return {
    projectName: config?.projectName || 'Untitled',
    context,
    prototypes: exportProtos,
    stats: { prototypes: exportProtos.length, groups: totalGroups, versions: totalVersions },
  };
}

function toMarkdown(data: ExportData): string {
  const lines: string[] = [];

  lines.push(`# ${data.projectName} — Project Export`);
  lines.push('');
  lines.push(`> Generated by Snap on ${new Date().toLocaleDateString()}`);
  lines.push(`> ${data.stats.prototypes} prototypes, ${data.stats.groups} groups, ${data.stats.versions} versions`);
  lines.push('');

  if (data.context) {
    lines.push('---');
    lines.push('');
    lines.push('## Project Context');
    lines.push('');
    lines.push(data.context);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## Prototype Hierarchy');
  lines.push('');

  for (const proto of data.prototypes) {
    lines.push(`### ${proto.name}`);
    if (proto.description) lines.push(`*${proto.description}*`);
    lines.push('');

    for (const group of proto.groups) {
      lines.push(`#### ${group.name}`);
      if (group.description) lines.push(group.description);
      if (group.brief) {
        lines.push('');
        lines.push('**Brief:**');
        lines.push(group.brief);
      }
      lines.push('');

      for (const [cat, scenarios] of Object.entries(group.categories)) {
        lines.push(`**${cat}**`);
        lines.push('');
        for (const scenario of scenarios) {
          const sub = scenario.subVersions[0];
          const subCount = scenario.subVersions.length > 1 ? ` (${scenario.subVersions.length} sub-versions)` : '';
          const tags = sub.tags.length > 0 ? ` [${sub.tags.join(', ')}]` : '';
          const star = sub.starred ? ' ★' : '';
          lines.push(`- **${scenario.name}**${subCount}${tags}${star}`);
          if (sub.description) lines.push(`  - ${sub.description}`);
          if (sub.notes) lines.push(`  - Note: ${sub.notes}`);
          if (sub.files.length > 0) {
            lines.push(`  - Files: ${sub.files.join(', ')}`);
          }
        }
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

export { buildExportData, toMarkdown };

export const exportCommand = new Command('export')
  .description('Export project structure for AI tools or collaboration')
  .option('--json', 'Output as structured JSON')
  .option('--clipboard', 'Copy to clipboard')
  .option('--group <id>', 'Export only a specific group')
  .action(async (opts: { json?: boolean; clipboard?: boolean; group?: string }) => {
    await ensureInit();

    const data = await buildExportData(opts.group);
    const output = opts.json ? JSON.stringify(data, null, 2) : toMarkdown(data);

    if (opts.clipboard) {
      try {
        const platform = process.platform;
        const cmd = platform === 'darwin' ? 'pbcopy' : platform === 'win32' ? 'clip' : 'xclip -selection clipboard';
        execSync(cmd, { input: output });
        console.log(chalk.green('✓') + ' Copied to clipboard');
        console.log(chalk.dim(`${data.stats.prototypes} prototypes, ${data.stats.groups} groups, ${data.stats.versions} versions`));
      } catch {
        console.log(chalk.yellow('Could not copy to clipboard. Printing to stdout instead:'));
        console.log(output);
      }
      return;
    }

    console.log(output);
  });
